service: shopify-node-serverless

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  bundle:
    linting: false
    caching: false

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  environment:
    SHOPIFY_API_KEY: ${file(./config.${opt:stage, 'dev'}.json):SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET_KEY: ${file(./config.${opt:stage, 'dev'}.json):SHOPIFY_API_SECRET_KEY}
    SHOPIFY_SCOPES: ${file(./config.${opt:stage, 'dev'}.json):SHOPIFY_SCOPES}
    SHOPIFY_HOST: ${file(./config.${opt:stage, 'dev'}.json):SHOPIFY_HOST}
    SHOPIFY_APP_NAME: ${file(./config.${opt:stage, 'dev'}.json):SHOPIFY_APP_NAME}

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: get

  authCallback:
    handler: handler.authCallback
    events:
      - http:
          path: auth/callback
          method: get